AWSTemplateFormatVersion: 2010-09-09
Description: Iac for Dal Vacation Home
Resources:
  LambdaRegister:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "LambdaRegister"
      Runtime: "nodejs20.x"
      Role: "arn:aws:iam::082497693506:role/LabRole" #replace it with your own LabRole ARN
      Handler: "index.handler"
      Timeout: 120
      MemorySize: 512
      Environment:
        Variables:
          UserDalVacationDynamoTableName: !Ref UserDalVacationDynamoTable
          DalVacationHomeUserPoolId: !Ref UserPool
          DalVacationHomeAppClientId: !Ref UserPoolClient
      Code:
        S3Bucket: "dalvacation-lambda-bucket-yuci" #replace it with your own S3bucket
        S3Key: "LambdaRegister.zip"

  LambdaConfirmUser:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "LambdaConfirmUser"
      Runtime: "nodejs20.x"
      Role: "arn:aws:iam::082497693506:role/LabRole" #replace it with your own LabRole ARN
      Handler: "index.handler"
      Timeout: 120
      MemorySize: 512
      Environment:
        Variables:
          DalVacationHomeUserPoolId: !Ref UserPool
          DalVacationHomeAppClientId: !Ref UserPoolClient
      Code:
        S3Bucket: "dalvacation-lambda-bucket-yuci" #replace it with your own S3bucket
        S3Key: "LambdaConfirmUser.zip"

  LambdaLogin1stFactor:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "LambdaLogin1stFactor"
      Runtime: "nodejs20.x"
      Role: "arn:aws:iam::082497693506:role/LabRole" #replace it with your own LabRole ARN
      Handler: "index.handler"
      Timeout: 120
      MemorySize: 512
      Environment:
        Variables:
          UserDalVacationDynamoTableName: !Ref UserDalVacationDynamoTable
          DalVacationHomeAppClientId: !Ref UserPoolClient
      Code:
        S3Bucket: "dalvacation-lambda-bucket-yuci" #replace it with your own S3bucket
        S3Key: "LambdaLogin1stFactor.zip"

  LambdaLogin2ndFactor:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "LambdaLogin2ndFactor"
      Runtime: "nodejs20.x"
      Role: "arn:aws:iam::082497693506:role/LabRole" #replace it with your own LabRole ARN
      Handler: "index.handler"
      Timeout: 120
      MemorySize: 512
      Environment:
        Variables:
          UserDalVacationDynamoTableName: !Ref UserDalVacationDynamoTable
      Code:
        S3Bucket: "dalvacation-lambda-bucket-yuci" #replace it with your own S3bucket
        S3Key: "LambdaLogin2ndFactor.zip"
  LambdaLogin3rdFactor:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "LambdaLogin3rdFactor"
      Runtime: "nodejs20.x"
      Role: "arn:aws:iam::082497693506:role/LabRole" #replace it with your own LabRole ARN
      Handler: "index.handler"
      Timeout: 120
      MemorySize: 512
      Environment:
        Variables:
          UserDalVacationDynamoTableName: !Ref UserDalVacationDynamoTable
      Code:
        S3Bucket: "dalvacation-lambda-bucket-yuci" #replace it with your own S3bucket
        S3Key: "LambdaLogin3rdFactor.zip"
  LambdaAddFeedback:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "LambdaAddFeedback"
      Runtime: "nodejs20.x"
      Role: "arn:aws:iam::082497693506:role/LabRole" #replace it with your own LabRole ARN
      Handler: "index.handler"
      Timeout: 120
      MemorySize: 512
      Environment:
        Variables:
          FeedbackDalVacationDynamoTableName: !Ref FeedbackDalVacationDynamoTable
          GOOGLE_API_ACCESS_TOKEN: "ya29.a0AXooCgsH7BffSH5-xxEa0_opSyaoRJLRdGZzVf7RAnGYLEiwAGPZA4HPBYjyjFAZo57NbktIju6lLtzZDbYP4D6gzEBcACECSKJXwItDpPRm0YpcTgY8IuwGnbBaU60e_7HJiM1y4JTNBHaJDXEEzpZWnnpJgxGNCB6ULZg0Ymbt9P2q0oBcCg5gntJZWf_UvQfufhKraiyYPC2x7rtAR8P_epkhI5qnV2qJeMzqXdg45TsI2S6fRlz6HdUNzia4bYrKVM_UYzkZGyeOJiWknXALC4v-cF2NsvRmHO_MB3pGACX6Lnc7lmMmDxeUKMcS-Vuxqyb4GjbPPPa9PdjEiOj_fT-lj3TaNuGMjeB9kH7x-0tn9WuD_zEdYPN7f2sZEx9dpurDoayohwNcSBrkqhd8QgbffCMaCgYKAbASARMSFQHGX2MieqUWPN4E67_Dbk2ApuUybg0422"
          API_ENDPOINT: "https://us-central1-aiplatform.googleapis.com/v1/projects/csci-5410-serverless-428001/locations/us-central1/publishers/google/models/gemini-1.5-flash-001:streamGenerateContent"
      Code:
        S3Bucket: "dalvacation-lambda-bucket-yuci" #replace it with your own S3bucket
        S3Key: "AddFeedback.zip"
  UserDalVacationDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UserDalVacation
      AttributeDefinitions:
        - AttributeName: "email"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "email"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  FeedbackDalVacationDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FeedbackDalVacation
      AttributeDefinitions:
        - AttributeName: "feedback_id"
          AttributeType: "S"
        - AttributeName: "timestamp"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "feedback_id"
          KeyType: "HASH"
        - AttributeName: "timestamp"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: DALVacationHomeUserPool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireNumbers: true
      MfaConfiguration: "OFF"

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: DALVacationHomeAppClient
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      SupportedIdentityProviders:
        - COGNITO

  # API GATEWAY

  UserAuthenticationApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: UserAuthenticationApiGateway

  UserAuthenticationApiAuthenticationResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref UserAuthenticationApiGateway
      ParentId: !GetAtt UserAuthenticationApiGateway.RootResourceId
      PathPart: "authentication"

  UserAuthenticationApiSignupResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref UserAuthenticationApiGateway
      ParentId: !GetAtt UserAuthenticationApiAuthenticationResource.ResourceId
      PathPart: "signup"

  UserAuthenticationApiLoginResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref UserAuthenticationApiGateway
      ParentId: !GetAtt UserAuthenticationApiAuthenticationResource.ResourceId
      PathPart: "login"

  UserAuthenticationApiSignupConfirmationResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref UserAuthenticationApiGateway
      ParentId: !GetAtt UserAuthenticationApiSignupResource.ResourceId
      PathPart: "confirmation"

  UserAuthenticationApiLogin1stResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref UserAuthenticationApiGateway
      ParentId: !GetAtt UserAuthenticationApiLoginResource.ResourceId
      PathPart: "1st"

  UserAuthenticationApiLogin2ndResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref UserAuthenticationApiGateway
      ParentId: !GetAtt UserAuthenticationApiLoginResource.ResourceId
      PathPart: "2nd"

  UserAuthenticationApiLogin3rdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref UserAuthenticationApiGateway
      ParentId: !GetAtt UserAuthenticationApiLoginResource.ResourceId
      PathPart: "3rd"
      
  SignUpMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref UserAuthenticationApiGateway
      ResourceId: !Ref UserAuthenticationApiSignupResource
      HttpMethod: POST
      AuthorizationType: NONE
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: "Empty"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: "'*'" # replace it with you own domain
      RequestParameters: {}
      RequestModels: {}
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS
        Uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaRegister.Arn}/invocations"
        Credentials: "arn:aws:iam::082497693506:role/LabRole"
        RequestTemplates:
          application/json: ""
        IntegrationResponses:
          - StatusCode: "200"
            ResponseTemplates:
              application/json: ""
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'" # replace it with you own domain

  ConfirmationMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref UserAuthenticationApiGateway
      ResourceId: !Ref UserAuthenticationApiSignupConfirmationResource
      HttpMethod: POST
      AuthorizationType: NONE
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: "Empty"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: "'*'" # replace it with you own domain
      RequestParameters: {}
      RequestModels: {}
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS
        Uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaConfirmUser.Arn}/invocations"
        Credentials: "arn:aws:iam::082497693506:role/LabRole"
        RequestTemplates:
          application/json: ""
        IntegrationResponses:
          - StatusCode: "200"
            ResponseTemplates:
              application/json: ""
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'" # replace it with you own domain

  FirstLoginMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref UserAuthenticationApiGateway
      ResourceId: !Ref UserAuthenticationApiLogin1stResource
      HttpMethod: POST
      AuthorizationType: NONE
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: "Empty"
          ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'" # replace it with you own domain
      RequestParameters: {}
      RequestModels: {}
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS
        Uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaLogin1stFactor.Arn}/invocations"
        Credentials: "arn:aws:iam::082497693506:role/LabRole"
        RequestTemplates:
          application/json: ""
        IntegrationResponses:
          - StatusCode: "200"
            ResponseTemplates:
              application/json: ""
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'" # replace it with you own domain

  SecondLoginMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref UserAuthenticationApiGateway
      ResourceId: !Ref UserAuthenticationApiLogin2ndResource
      HttpMethod: POST
      AuthorizationType: NONE
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: "Empty"
          ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'" # replace it with you own domain
      RequestParameters: {}
      RequestModels: {}
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS
        Uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaLogin2ndFactor.Arn}/invocations"
        Credentials: "arn:aws:iam::082497693506:role/LabRole"
        RequestTemplates:
          application/json: ""
        IntegrationResponses:
          - StatusCode: "200"
            ResponseTemplates:
              application/json: ""
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'" # replace it with you own domain

  ThirdLoginMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref UserAuthenticationApiGateway
      ResourceId: !Ref UserAuthenticationApiLogin3rdResource
      HttpMethod: POST
      AuthorizationType: NONE
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: "Empty"
          ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'" # replace it with you own domain
      RequestParameters: {}
      RequestModels: {}
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS
        Uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaLogin3rdFactor.Arn}/invocations"
        Credentials: "arn:aws:iam::082497693506:role/LabRole"
        RequestTemplates:
          application/json: ""
        IntegrationResponses:
          - StatusCode: "200"
            ResponseTemplates:
              application/json: ""
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'" # replace it with you own domain

  UserAuthenticationApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref UserAuthenticationApiGateway
      DeploymentId: !Ref UserAuthenticationApiDeployment
      StageName: v1

  UserAuthenticationApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - SignUpMethod
      - ConfirmationMethod
      - FirstLoginMethod
      - SecondLoginMethod
      - ThirdLoginMethod
    Properties:
      RestApiId: !Ref UserAuthenticationApiGateway
